### ISSUE TITLE
[Feature Request]: Icon override with entity/block model

### ISSUE THREAD

**Issue by tazzanmc** [terrarium-earth/hercules#231] opened 2024-06-02 23:51 UTC
### Solution(s)

I believe it would be a very nice QoL feature if you could use the existing entity/block model renderer within Heracles to override the icons of quests and tasks. This way, you could have any quest or task display itself as a mob, or display a different mob on a kill task for whatever reason. Attached image is a mock-up I created to show what this might look like.
![entity model override mockup](https://github.com/terrarium-earth/Heracles/assets/35785712/8a8ba4aa-61e0-40e2-b578-40f983145b82)

### Mod Version

1.1.12

### Mod Loader Version

1.20.1 47.2.21

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment] 2024-06-02 23:52
duplicate of #130

**Closed as completed by ThatGravyBoat** 2024-06-02 23:52 UTC
Labels: enhancement
