### ISSUE TITLE
[Feature Request]: Make escape take you to the questbook from the quest

### ISSUE THREAD

**Issue by jorjro** [terrarium-earth/hercules#238] opened 2024-06-17 12:19 UTC
### Is your feature request related to a problem?

I'm always frustrated when I click on a quest and I press escape to go back to the questbook and it closes it completely.

### Solution(s)

Make escape take you back to the questbook when pressed inside a quest and close the questbook when outside the quest.

### Describe alternatives you've considered

Add a config option for it.

### Mod Version

1.1.13

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Additional context

It's more intuitive for people coming over with muscle memory from FTB quests.

**Comment by lonevox** [comment] 2024-06-26 13:15
I think Alt + ← for going back to the quest book and Alt + → for going forwards to the last opened quest would work well too. These keybinds are the standard for backwards and forwards, which many mice with additional buttons are pre-bound with, so you'd be able to more easily navigate the quests with the mouse.

**Comment by lonevox** [comment] 2024-06-26 13:18
This is a duplicate of #90

**Closed as completed** 2024-10-02 10:17 UTC
Labels: enhancement
