### ISSUE TITLE
[Bug]: EMI buttons render on the Quests screen

### ISSUE THREAD

**Issue by lumiscosity** [terrarium-earth/hercules#30] opened 2023-06-14 20:59 UTC
### Bug Description

The EMI config and recipe tree buttons appear on the quests menu.

### How to Reproduce?

Install EMI and open the quests menu.

### Expected Behavior

The buttons do not appear.

### Version

0.0.2

### Mod Loader Version

1.20.1, 0.14.21

### Mod Loader

Fabric

### Logs or additional context

"currently EMI will render in any HandledScreen. why are they using a HandledScreen" - Emi, when contacted about the bug (idk what any of that means i haven't touched a line of minecraft mod code before)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment] 2023-06-14 21:14
You can tell emi I wanted it so that I could have it synced and know when a GUI was open but a lot of mods seem to not check if a menu actually has slots so I will just change it to a screen like I said in the other issue, if you encounter anymore issues with mods showing up in the screen please do not report it to the repo or them because it is like a 99% chance the same bug

**Comment by ThatGravyBoat** [comment] 2023-06-14 21:36
ill have a fix for it in a few

**Comment by ThatGravyBoat** [comment] 2023-06-14 21:37
but so I dont forget to close both duplicate of #29

**Closed as not planned by ThatGravyBoat** 2023-06-14 21:37 UTC
Labels: bug
