### ISSUE TITLE
[Feature Request]: Nested groups with a dropdown, similar to FTB quests

### ISSUE THREAD

**Issue by Auseawesome** [terrarium-earth/hercules#182] opened 2024-02-20 22:01 UTC
### Is your feature request related to a problem?

Groups quickly fill up sidebar, hard to find what you need

### Solution(s)

Add meta groups or categories allowing you to group quest groups like how FTB quests does it. A little drop down arrow to expan the meta group and show all the sub groups

### Describe alternatives you've considered

Hiding whole quest groups until quests inside are visible, links on to #181 

### Mod Version

1.1.9

### Mod Loader Version

47.1.96

### Mod Loader

NeoForge

**Comment by ThatGravyBoat** [comment] 2024-02-20 22:10
Duplicate of #113

**Closed as not planned by ThatGravyBoat** 2024-02-20 22:10 UTC
Labels: enhancement

**Comment by Auseawesome** [comment] 2024-02-20 22:11
I looked for issues, musta missed it cos of the typo in the title, mb
