### ISSUE TITLE
[Bug]: dont save quest (bug with Ä Ü Ö)

### ISSUE THREAD

**Issue by MrHaiopei** [terrarium-earth/hercules#44] opened 2023-07-22 17:22 UTC
### Bug Description

we need a save botton after change/edit a Quest (text/reward) he don´t save this.
next problem is, i think it is Ä Ü Ö bug in Overview and remove my progress (my problem is i come from germany Ä Ü Ö are in many words and i forgot to change ist to.) Change to: Ä =Ae | Ö =Oe | Ü = Ue.
Pls help me i like your Mod so much i want to make quest without problems but after 30 Quest he delete 20 Quest and 3 houre progress is done.

### How to Reproduce?

Add a Quest 
After give the Quest A name with Ä Ü Ö
or in Overview Text is Ä Ü Ö 
or in Subtitle is Ä Ü Ö
i think this is the Problem

### Version

0.0.5 and 0.0.6

### Mod Loader Version

1.20.1 - 47.1.39

### Mod Loader

Forge

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [x] I have checked the FAQ (if one is present) and my issue is not listed
- [x] I have verified that I am using the latest version of the mod
- [x] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment] 2023-07-22 17:41
Things are automatically saved, a save button would not do anything.

**Comment by ThatGravyBoat** [comment] 2023-07-22 17:52
I cant reproduce any issues with those characters in titles, subtitles, or overviews it works perfectly fine for me.

**Comment by HavocStudio2** [comment] 2023-07-30 14:14
> I cant reproduce any issues with those characters in titles, subtitles, or overviews it works perfectly fine for me.

I'm having the same issue with the quest not saving the data, I have been messing around with it and found out that after the 3rd quest and you try to link the quest up and change the icon background and icon close out of the menu and reopen it, it does not save the changes. This is also with the mod that you gave me.

**Comment by ThatGravyBoat** [comment] 2023-07-30 15:10
So we dont have 2 reports with similar reportings I am closing this in favor of #45

**Closed as not planned by ThatGravyBoat** 2023-07-30 15:10 UTC
Labels: bug, Cant Reproduce
